### ISSUE TITLE
Details of SYNTHIA-Seq dataset

### ISSUE THREAD

**Issue by EDENpraseHAZARD** [Dayan-Guan/DA-VSN#3]
Hi author, I have downloaded SYNTHIA-Seq, but I found there are 'Stereo_Left' and 'Stereo_Right' folders. And each contains 'Omni_B', 'Omni_F', 'Omni_L' and 'Omni_R'. I wonder which one is used for training.

**Comment by Dayan-Guan** [comment]
Hi @EDENpraseHAZARD , we use 'Stereo_Left' (the same as in the Cityscapes-Seq dataset) and 'Omni_F' (the F means Front).

**Comment by EDENpraseHAZARD** [comment]
Thanks.
