### ISSUE TITLE
Could you please provide 'estimated_optical_flow' for training DA-VSN

### ISSUE THREAD

**Issue by ldkong1205** [Dayan-Guan/DA-VSN#5]
Hi @Dayan-Guan , thank you for open-sourcing your work!

I am trying to follow this work. For training DA-VSN from scratch, the optical flows (for the 3 datasets used in your paper) estimated by FlowNet2 are needed. However, the instruction in your README only includes the evaluation part. I also see from the recent issues that you have provided the code and more instructions for the training part. But the code is not a complete one I guess so I cannot generate the optical flows with it.

Could you please provide your generated optical flows for all 3 datasets used in your paper? It would save us time. Or could you please have a look again at the provided 'Code_for_optical_flow_estimation'? So that it is runnable for generating optical flows on our own.

Thanks in advance!

Regards

**Comment by Dayan-Guan** [comment]
The estimated optical flow of all datasets can be accessed via the link below:
https://drive.google.com/drive/folders/1i_-yw9rS7-aa7Cn5ilIMbkUKwr1JpUFA?usp=sharing
